#!/bin/bash
# Dependencies:Bowtie2
# Install:
#   conda install -c bioconda bowtie2

# Activate the Conda environment -- if need be
eval "$(conda shell.bash hook)"
conda activate bowtie2_env

# Define paths
FASTQ_PATH="/temporario2/9290665/DADOS_ALZHEIMER/laske/cleaned_reads_1"
INDEX_PATH="/temporario2/9290665/DADOS_ALZHEIMER/laske/indexed_fna"
OUTPUT_PATH="/temporario2/9290665/DADOS_ALZHEIMER/laske/fna_reads_aligned"

# Create the output directory if it doesn't exist
mkdir -p $OUTPUT_PATH

# Loop through all *_1.fastq.gz files in the FASTQ_PATH
for FILE1 in "$FASTQ_PATH"/*_filtered_aligned_R1.fastq; do
  # Get the base name of the sample (without the _R1.fastq suffix)
  BASENAME=$(basename "$FILE1" "_filtered_aligned_R1.fastq")

  # Define the corresponding file for the _2.fastq.gz pair
  FILE2="${FASTQ_PATH}/${BASENAME}_filtered_aligned_R2.fastq"
  INDEX_FILE="${INDEX_PATH}/${BASENAME}_fna_indexed"

 # Check if both read files exist
  if [[ -f "$FILE1" && -f "$FILE2" ]]; then
    # Print sample name
    echo "Processing sample: $BASENAME"
    # Alignment with Bowtie2
    bowtie2 -x "$INDEX_FILE" \
      -1 "$FILE1" \
      -2 "$FILE2" \
      --threads 8 \
      -S "$OUTPUT_PATH/${BASENAME}_aligned_fna.sam"
  else
    echo "Warning: Missing pair for $BASENAME. Skipping alignment."
  fi
done
