#!/bin/bash -v
#SBATCH --partition=SP2
#SBATCH --ntasks=1              # number of tasks / mpi processes
#SBATCH --cpus-per-task=16       # Number OpenMP Threads per process
#SBATCH -J megahit-1
#SBATCH --time=8-00:00:00
#SBATCH --output=megahit1.out
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-user=gabriela.castilho.martins@usp.br

# Ambiente para uso eficiente de múltiplos threads
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OPENBLAS_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

echo $SLURM_JOB_ID              #ID of job allocation
echo $SLURM_SUBMIT_DIR          #Directory job where was submitted
echo $SLURM_JOB_NODELIST        #File containing allocated hostnames
echo $SLURM_NTASKS              #Total number of cores for job

#run the application:
bash /temporario2/9290665/caminho_script/script.sh
