#!/bin/bash
# Dependencies: Bowtie2
# Install:
#   conda install -c bioconda bowtie2

# Activate the Conda environment -- if need be
eval "$(conda shell.bash hook)"
conda activate bowtie2_env

# Define paths
FASTQ_PATH="/temporario2/9290665/DADOS_ALZHEIMER/laske/outputs_fastp"
GENOME_INDEX_PATH="/temporario2/9290665/genoma_humano/GRCh38_index"
OUTPUT_PATH="/temporario2/9290665/DADOS_ALZHEIMER/laske/outputs_bowtie2"

# Create the output directory if it doesn't exist
mkdir -p $OUTPUT_PATH

# Loop through all *_1.fastq.gz files in the FASTQ_PATH
for FILE1 in $FASTQ_PATH/*_1.fastq.gz; do
  # Get the base name of the sample (without the _1.fastq.gz suffix)
  BASENAME=$(basename $FILE1 _1.fastq.gz)
  
  # Define the corresponding file for the _2.fastq.gz pair
  FILE2="${FASTQ_PATH}/${BASENAME}_2.fastq.gz"

  # Alignment with Bowtie2
  bowtie2 -x $GENOME_INDEX_PATH \
    -1 $FILE1 \
    -2 $FILE2 \
    --threads 8 \
    -S $OUTPUT_PATH/${BASENAME}_aligned.sam

done

# NOTE: Bowtie2 generates a single output file containing the alignment of both sequences (forward and reverse).
