#!/bin/bash
# Dependencies: Bowtie2, wget, gunzip
# Install:
#   conda install -c bioconda bowtie2
#   sudo apt install wget gzip  # (For Ubuntu/Debian)
# Downloading the human genome and indexing using Bowtie2
#!/bin/bash
eval "$(conda shell.bash hook)"

# Activate the Conda environment with Bowtie2 (only if need be)
conda activate bowtie2_env

# Define the directory where the genome will be downloaded
GENOME_DIR=~/human_genome

# Download the human genome (GRCh38)
cd $GENOME_DIR
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_genomic.fna.gz

# Decompress the downloaded file
gunzip GCF_000001405.40_GRCh38.p14_genomic.fna.gz

# Create the genome index with Bowtie2
bowtie2-build GCF_000001405.40_GRCh38.p14_genomic.fna GRCh38_index

echo "Human genome index successfully created!"
